version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: oauth-demo-app
    depends_on:
      - redis
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      # OAuth2 등록 정보
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:     "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID:      "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET:  "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID:      "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET: "${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}"

      # JWT (두 가지 네이밍 모두 주입)
      APP_AUTH_TOKEN_SECRET:                 "${APP_AUTH_TOKEN_SECRET}"
      APP_AUTH_TOKENSECRET:                  "${APP_AUTH_TOKEN_SECRET}"
      APP_AUTH_ACCESS_TOKEN_EXPIRATION_MSEC:   "${APP_AUTH_ACCESS_TOKEN_EXPIRATION_MSEC}"
      APP_AUTH_ACCESSTOKENEXPIRATIONMSEC:      "${APP_AUTH_ACCESS_TOKEN_EXPIRATION_MSEC}"
      APP_AUTH_REFRESH_TOKEN_EXPIRATION_MSEC:  "${APP_AUTH_REFRESH_TOKEN_EXPIRATION_MSEC}"
      APP_AUTH_REFRESHTOKENEXPIRATIONMSEC:     "${APP_AUTH_REFRESH_TOKEN_EXPIRATION_MSEC}"

      # Redis
      SPRING_DATA_REDIS_HOST: "${SPRING_DATA_REDIS_HOST}"
      SPRING_DATA_REDIS_PORT: "${SPRING_DATA_REDIS_PORT}"
    restart: unless-stopped
