# application.yml
server:
  port: 5050

spring:
  profiles:
    active: private

  thymeleaf:
    cache: false

  data:
    redis:
      host: localhost            # Redis 서버 호스트
      port: 6379                 # Redis 서버 포트
      password: ${REDIS_PASSWORD:}  # 비밀번호가 있다면 환경변수로 주입, 없으면 빈 값
      timeout: 6000ms            # 커넥션 타임아웃 (밀리초)
      lettuce:
        shutdown-timeout: 100ms  # Lettuce 클라이언트 종료 타임아웃
        pool:
          max-active: 8          # 커넥션 최대 개수
          max-idle: 8            # 유휴 커넥션 최대 개수
          min-idle: 0            # 유휴 커넥션 최소 개수
          max-wait: 3000ms       # 커넥션 획득 최대 대기 시간

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            authorization-grant-type: authorization_code
            redirect-uri: "${app.baseUrl}/login/oauth2/code/google"
            scope: openid, profile, email

          kakao:
            provider: kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "${app.baseUrl}/login/oauth2/code/kakao"
            scope: profile_image, profile_nickname, account_email

          naver:
            provider: naver
            authorization-grant-type: authorization_code
            redirect-uri: "${app.baseUrl}/login/oauth2/code/naver"
            scope: name, email

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  baseUrl: http://localhost:${server.port}

logging:
  level:
    org.springframework.security: DEBUG
